name: PR Sanity Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          npm install
          npm install --save firebase
      - name: Lint check
        run: |
          npm run lint
      - name: run emulator firebaise
        run: |
          npm run firebase:e
      - name: test
        run: |
          npm run test
